### ISSUE TITLE
Propper Tests

### ISSUE THREAD

**Issue by adamisntdead** [exogen/graphql-markdown#28]
Might be a good idea to separate out the tests from that `https://graphbrainz.herokuapp.com/` API, and break it up into unit tests, rather than that snapshot test.

Would make it easier to add new features too

**Comment by exogen** [comment]
I think at some point I'd like to migrate it to Jest as well, the module mocking situation (for situations when needed) is much easier there!

**Comment by adamisntdead** [comment]
You could setup something like a simple little [graphql-yoga](https://github.com/prismagraphql/graphql-yoga) server and run tests off that, If I get time later I will have a look at it

**Comment by exogen** [comment]
Still not perfect, but improved considerably in #35.
