### ISSUE TITLE
Is this project being updated anymore?

### ISSUE THREAD

**Issue by jaygurnani** [exogen/graphql-markdown#57]
Hi there,

I tried following the instructions to generate a markdown file, but this project seems out of date. I get the following error when trying to generate a markdown file:

`(node:13971) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__schema' of undefined
    at renderSchema (/Users/jgurnani/Code/graphql-markdown/node_modules/graphql-markdown/src/renderSchema.js:112:14)
    at /Users/jgurnani/Code/graphql-markdown/node_modules/graphql-markdown/src/index.js:111:9`

**Comment by jaygurnani** [comment]
Missing header. Issue can be fixed

**Comment by exogen** [comment]
Good to know, thanks!
