### ISSUE TITLE
Prettier: Sync codebase with prettier config?

### ISSUE THREAD

**Issue by tony** [exogen/graphql-markdown#62]
I automatically format on save so this is causing a large rewrite/diff for me. I assume the intent (via eslint + prettier) is to stick to some consistent formatting

It'd potentially make contributions easier since there wouldn't be unrelated formatting in the diffs

Do you have any styling preferences? 

I have a fork of graphql-markdown where I'm going to pick a formatter, so this would make contributing PRs back easier. It could also make it easier for other contributors. I got this habit from other projects 🤷‍♂️

**Comment by exogen** [comment]
So the current Prettier settings in the `eslintrc` are supposed to be applied, but I assume what's happening is that the autoformat plugin uses the Prettier defaults instead, since it expects Prettier preferences to be in `prettierrc` and not `eslintrc`.

We can stick those in `prettierrc` as well like you've done in #64.

**Comment by tony** [comment]
> So the current Prettier settings in the eslintrc are supposed to be applied,

Maybe, but that's news to me.  I assume prettier v1 and v2 wants a `.prettierrc` file

Do you want to use prettier v2? The only reason I bring it up is I think editor plugins may use v2, but not sure. For me personally in vim, it uses a prettier bin that's v2 and doesn't check `node_modules/`

**Comment by tony** [comment]
Also: 

- #63: Rebased + Added `.prettierrc`
- #64: Rebased

**Comment by exogen** [comment]
> Maybe, but that's news to me. I assume prettier v1 and v2 wants a .prettierrc file

I meant that we don't run `prettier` itself currently at all. Only ESLint with Prettier as the formatter. So any Prettier editor plugin won't know anything about the settings, really an ESLint formatter should be running in the editor instead

**Comment by exogen** [comment]
There is now a `.prettierrc.js`, so editor integrations should be able to find the project's config more easily.
