### ISSUE TITLE
Schema with multiple files

### ISSUE THREAD

**Issue by wagnerlduarte** [exogen/graphql-markdown#77]
In my case, my schema is separeted in multiple files as the image below
![image](https://user-images.githubusercontent.com/17439470/127390039-f9a4e6a0-27b5-4f8c-9a91-92f201997204.png)

Currently is possible generate a markdown when have a case like mine?
I tried add multiple files as parameter, but I got error.

The solution in my case was transfer content of all the files to `schema.graphql` and use the `graphql-markdown` to generate a `file.md`.

My suggestion is create a possibility to this case when have a schema splited in multiple files. Make sense? It's possible?

**Comment by wagnerlduarte** [comment]
@exogen @nextdude

**Comment by GabrielBarross** [comment]
Do you already have any solutions for this case?
@exogen @nextdude

**Comment by nextdude-mdsol** [comment]
@wagnerlduarte @GabrielBarross not really, but

```
cat types/*.graphql | graphql-markdown /dev/stdin
```

might work if your system is linux or mac (has `/dev/stdin`). Basically, you're limited to a single file given how `graphql-markdown` parses its arguments. This example combines your files and pipes the resulting output to `graphql-markdown` passing in `dev./stdin` as the file (which represents the piped input).

**Comment by hiagolcm** [comment]
I joined all .graphql files programmatically using some extra libs. And the attached it to a git hook

 ```
 const fs = require('fs')

const { loadFilesSync } = require('@graphql-tools/load-files')
const { mergeTypeDefs } = require('@graphql-tools/merge')
const graphql = require('graphql')
const {
  loadSchemaJSON,
  renderSchema,
} = require('graphql-markdown')

const SCHEMA_PATH = `${__dirname}/../graphql/**/*.graphql`
const BUNDLE_PATH = `${__dirname}/../joined.graphql`
const MARKDOWN_PATH = `${__dirname}/../docs/README.md`

;(async () => {
  // Generate bundle
  const loadedFiles = loadFilesSync(SCHEMA_PATH)
  const typeDefs = mergeTypeDefs(loadedFiles)
  const printedTypeDefs = graphql.print(typeDefs)
  fs.writeFileSync(BUNDLE_PATH, printedTypeDefs)

  // Generate markdown
  fs.unlinkSync(MARKDOWN_PATH)
  const schema = await loadSchemaJSON(BUNDLE_PATH, { graphql })
  renderSchema(schema, {
    title: 'search-graphql',
    prologue:
      '# VTEX Search GraphQL\n\nThis app exports a GraphQL schema for search results on VTEX Stores.\n\nThe default implementation for this schema is on [vtex.search-resolver](https://github.com/vtex-apps/search-resolver) app.\n\n### Usage\n\nTo use it in your app, decalre it on your manifest file like:\n```\n"dependencies": {\n  "vtex.search-graphql": "0.x"\n}\n```\n\nYou may then use it in your front end component queries, for example, write file `productQuery.gql`:\n```graphql\nquery ProductQuery($slug: String) {\n  product(identifier: { field: slug, value: $slug}) @context(provider: "vtex.search-graphql") {\n    productName\n  }\n}\n```\n\nTo resolve this query, you need to have a app that implements the schema declared in this app, such as: [vtex.search-resolver](https://github.com/vtex-apps/search-resolver)',
    printer: (doc) => fs.appendFileSync(MARKDOWN_PATH, doc)
  })

  // Delete temp file
  fs.unlinkSync(BUNDLE_PATH)
})()

```

**Comment by wagnerlduarte** [comment]
@nextdude-mdsol @hiagolcm thank you for your support to solve this problem guys!

I solved this problem creating a script to merge `*.graphql` files using [`graphql-schema-utilities`](https://github.com/awslabs/graphql-schema-utilities)
After that I got the file generated and run the `graphql-markdown` using this file.

It worked fine and I will share with you the steps for those who want to do the same here:

1. Create a file named `graphql-markdown-generator.js` with the code below

```
const { execSync } = require('child_process')

const argv = require('minimist')(process.argv.slice(2))

const DEFAULT_GRAPHQL_PATH = './graphql/**/*.{gql,graphql}'
const DEFAULT_MERGED_PATH = './merged.graphql'
const DEFAULT_MARKDOWN_PATH = './schema.md'

const GRAPHQL_ARG = argv['graphql-path']
const MERGED_ARG = argv['merged-path']
const MARKDOWN_ARG = argv['markdown-path']

const GRAPHQL_PATH = GRAPHQL_ARG || DEFAULT_GRAPHQL_PATH
const MERGED_PATH = MERGED_ARG || DEFAULT_MERGED_PATH
const MARKDOWN_PATH = MARKDOWN_ARG || DEFAULT_MARKDOWN_PATH

execSync(
  `graphql-schema-utilities -s "${GRAPHQL_PATH}" -o ${MERGED_PATH} && graphql-markdown ${MERGED_PATH} > ${MARKDOWN_PATH} && rm ${MERGED_PATH}`
)
```

2. In the `package.json` create a script named `graphql-markdown` as below

```
{
  ...
  "scripts": {
    "graphql-markdown": "node graphql-markdown-generator.js",
    ...
  },
  ...
}
```

3. In the `package.json` add in your `devDependencies` as below
```
{
  ...
  "devDependencies": {
    "graphql": "^15.0.0",
    "graphql-markdown": "^6.0.0",
   "graphql-schema-utilities": "^1.1.3",
    ...
  },
  ...
}
```

4. Run your script using `yarn graphql-markdown` to get a `schema.md` with your documentation 🏆
