### ISSUE TITLE
Loading schema fails with graphql v16+

### ISSUE THREAD

**Issue by nextdude-mdsol** [exogen/graphql-markdown#86]
Version 16 of `graphql` library removes support for positional arguments in call to `graphql.graphql()` used in `src/loadSchemaJSON.js` method `schemaToJSON` (line 24). The fix is to simply pass the schema and introspection query in an object instead.

**Comment by nextdude** [comment]
Submitted a [PR](https://github.com/exogen/graphql-markdown/pull/87) to fix this.

**Comment by exogen** [comment]
Released in [v6.1.0](https://github.com/exogen/graphql-markdown/releases/tag/v6.1.0). Thanks!
