### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by AndyEdmonds** [exogen/graphql-markdown#90]
Much as I like this product, and found it a great way to solve a documentation problem in a hurry, it doesn't seem to include subscriptions.

My GraphQL SaaS (https://darl.dev/graphql) has subscriptions.  Can we have documentation for these too please?

**Comment by exogen** [comment]
Fixed in #70 and published in [v7.1.0](https://github.com/exogen/graphql-markdown/releases/tag/v7.1.0)!
