### ISSUE TITLE
Support for multiple directives

### ISSUE THREAD

**Issue by fmontorsi-equinix** [exogen/graphql-markdown#99]
Hi,
I have a graphQL model named 'test.graphql' using 2 field directives on the same field:

```
directive @goTag(
	key: String!
	value: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

type MyType {
    assignedTo: String! @goTag(key: "json", value: "assigned_to") @goTag(key: "bson", value: "assigned_to")
}
```

this works just fine using https://gqlgen.com/ to produce Go code with the intended structure (in this case with the "right" struct tags).
However graphql-markdown does not accept the use of 2 field directives on the same field:

```
# graphql-markdown test.graphql 
/usr/local/lib/node_modules/graphql-markdown/node_modules/graphql/validation/validate.js:135
    throw new Error(errors.map((error) => error.message).join('\n\n'));
          ^

Error: The directive "@goTag" can only be used once at this location.
    at assertValidSDL (/usr/local/lib/node_modules/graphql-markdown/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/usr/local/lib/node_modules/graphql-markdown/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at Object.buildSchema (/usr/local/lib/node_modules/graphql-markdown/node_modules/graphql/utilities/buildASTSchema.js:109:10)
    at /usr/local/lib/node_modules/graphql-markdown/src/loadSchemaJSON.js:46:52
```

Is it possible to fix or workaround this limitation? 

Thanks!

**Comment by exogen** [comment]
Just did some digging into this! In the GraphQL spec I noticed a curious wording for the `UniqueDirectivesPerLocationRule`:

>  A GraphQL document is only valid if all non-repeatable directives at a given location are uniquely named.

The "non-repeatable" part made me think maybe there were "repeatable" directives, so I searched the spec for that. Sure enough, you can specify a directive as `repeatable` in the schema:

https://spec.graphql.org/draft/#example-67869

Yours would look like:

```graphql
directive @goTag(
	key: String!
	value: String
) repeatable on INPUT_FIELD_DEFINITION | FIELD_DEFINITION
```

When you do that, it works!
